### ISSUE TITLE
Cant Connect : mod_delay error

### ISSUE THREAD

**Issue by bonnebulle** [kibatic/docker-proftpd#3]
Thanks for this Docker solution !

I cant FTP connect (using Filezilla, in LAN)
Maybe I better do a issue on a proftpd forum...
let me know

----

I have an error in my log ( I can ignore it ) :
```bash
mod_delay/0.7: no DelayOnEvent rules configured with "DelayTable none" in effect, disabling module
```
----

I also have an error saying username:username not exists.
But, I already check/create the user and group...
```bash
chown: invalid group: 'username:username'
```

----

Resultat :
On Filezilla I have an error too (but password looks great) :
```bash
Error:	Connection closed by server
Error:	Could not connect to server
```

And ftp ( looks $(passwd username) dont works like I do ) :
````bash
ftp ftp://@192.168.1.23
Connected to 192.168.1.23.
220 ProFTPD Server (Debian) [192.168.1.23]
331 Password required for ftp://
Password: 
530 Login incorrect.
ftp: Login failed.
Remote system type is UNIX.
Using binary mode to transfer files.
````

----

My config :
```yml
version: '3.7'
services:
  proftpd:
    image: kibatic/proftpd
    network_mode: "host"
    restart: unless-stopped
    environment:
      FTP_LIST: "username:password"
      USERADD_OPTIONS: "-o --gid 33 --uid 33"
      # optional : default to 50000 and 50100
      # My NAT is open...
      PASSIVE_MIN_PORT: 1024
      PASSIVE_MAX_PORT: 1035
      # optional : default to undefined
      MASQUERADE_ADDRESS: ftp.mydomaine.cow
    volumes:
      - "/media/HDD//:/home/username"
```

Thanks
